version: "3.7"
services:

## --------------------------- PIOLI DB --------------------------- ##

  pioli:
    image: bancodedadospioli:latest
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - talkhub

    environment:
      - DATABASE_URL=postgresql://postgres:894291802448b50603a3ca64f5f43f01@postgres:5432/bancodedadospioli
      - NODE_ENV=production
      - PORT=3456

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.pioli.rule=Host(`pioli.talkhub.me`)
        - traefik.http.routers.pioli.entrypoints=websecure
        - traefik.http.routers.pioli.tls.certresolver=letsencryptresolver
        - traefik.http.services.pioli.loadbalancer.server.port=3456
        - traefik.http.routers.pioli.service=pioli

## --------------------------- PIOLI DB --------------------------- ##

networks:
  talkhub:
    external: true
    name: talkhub
